# Generated by Django 3.2.18 on 2024-12-11 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('User', '0007_specialist_is_deleted'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clinic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('bio', models.TextField()),
                ('code', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('IsAvailable', models.BooleanField(default=1)),
                ('AvaiableTimeFrom', models.DateField(blank=True, null=True)),
                ('AvaiableTimeTo', models.DateField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('Specialist', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Clinic', to='User.specialist')),
            ],
        ),
    ]
