# Generated by Django 3.2.18 on 2024-12-11 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('User', '0006_specialist_organization'),
    ]

    operations = [
        migrations.CreateModel(
            name='patient',
            fields=[
                ('customuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='User.customuser')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('profile_img', models.ImageField(blank=True, default='/patient/account.png', null=True, upload_to='patient')),
                ('birth_date', models.DateField(null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('Organization', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Clinic', to='User.organization')),
            ],
            options={
                'verbose_name': 'patient',
                'verbose_name_plural': 'patient',
                'ordering': ['id'],
            },
            bases=('User.customuser',),
        ),
    ]
