# Generated by Django 3.2.18 on 2024-12-11 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0006_specialist_organization'),
        ('Appointments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctoravailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DateFrom', models.TimeField()),
                ('DateTo', models.TimeField()),
                ('LevelImportant', models.CharField(blank=True, choices=[('important', '1'), ('Mid', '2'), ('normal', '3')], max_length=20)),
                ('TimeAdd', models.DateTimeField(auto_now=True)),
                ('Status', models.BooleanField(default=False)),
                ('Day', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Doctoravailability', to='Appointments.days')),
                ('Doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin', to='User.administrator')),
            ],
        ),
    ]
