# Generated by Django 3.2.18 on 2024-12-11 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appointments', '0002_doctoravailability'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctoravailability',
            name='Status',
            field=models.CharField(choices=[('Process', 'Rejected by the administration'), ('Cancel', 'Cancel'), ('Rejected', 'Rejected by the administration'), ('waiting', 'waiting'), ('approval', 'approval'), ('AnotherDate', 'AnotherDate')], default=1, max_length=50),
        ),
    ]
