# Generated by Django 3.2.18 on 2024-12-11 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_administrator_organization_specialist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administrator',
            name='Specialist',
            field=models.ManyToManyField(blank=True, related_name='administrators', to='User.Specialist'),
        ),
    ]
