# Generated by Django 3.2.18 on 2024-12-11 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0004_auto_20241211_1128'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='code',
        ),
        migrations.AlterField(
            model_name='organization',
            name='org_id',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
    ]
