# Generated by Django 3.2.18 on 2024-12-11 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0005_auto_20241211_1142'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialist',
            name='Organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Specialists', to='User.organization'),
        ),
    ]
