# Generated by Django 3.2.18 on 2024-12-11 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0006_specialist_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialist',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
